### ISSUE TITLE
raise RuntimeError("No audio I/O backend is available.")

### ISSUE THREAD

**Issue by mericmo** [facebookresearch/ImageBind#39]
error info:
D:\soft\anaconda3\envs\ImageBind\lib\site-packages\torchvision\transforms\_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
Traceback (most recent call last):
  File "E:\github\ImageBind\test.py", line 21, in <module>
    ModalityType.AUDIO: data.load_and_transform_audio_data(audio_paths, device),
  File "E:\github\ImageBind\data.py", line 135, in load_and_transform_audio_data
    waveform, sr = torchaudio.load(audio_path)
  File "D:\soft\anaconda3\envs\ImageBind\lib\site-packages\torchaudio\backend\no_backend.py", line 16, in load
    raise RuntimeError("No audio I/O backend is available.")
RuntimeError: No audio I/O backend is available.

**Comment by mericmo** [comment]
done
